from __future__ import annotations

from datetime import datetime, timezone
import re
from typing import Any, Dict, List, Optional
from uuid import uuid4

from fastapi.responses import JSONResponse

from ..acvp_mldsa.errors import AcvpSchemaError
from ..acvp_mldsa.expected import generate_expected_results_from_prompt
from ..acvp_mldsa.validators import validate_mldsa_response, validate_mldsa_vector_set
from ..acvp_parser import normalize_acvp_json, summarize_vector_set
from ..crypto_oracle.mldsa_errors import MldsaOracleError, MldsaOracleInputError
from ..models import AcvpV1TestSessionCreateRequest, AcvpV1VectorSetGenerateRequest
from ..report import build_report
from ..validator import validate
from .capabilities import (
    negotiate_mldsa_capabilities,
    validate_registration_container,
)
from .vector_generation import (
    DEFAULT_TESTS_PER_GROUP,
    GENERATION_PROFILE,
    MAX_TESTS_PER_GROUP,
    fallback_campaign_seed,
    generate_vector_sets_from_negotiated_capabilities,
)


SKELETON_PROFILE = "local-fips204-skeleton"
SKELETON_METADATA: Dict[str, Any] = {
    "productionReady": False,
    "profile": SKELETON_PROFILE,
    "demoOnly": True,
    "notProductionAcvp": True,
}

NIST_REFERENCES = [
    "https://pages.nist.gov/ACVP/draft-fussell-acvp-spec.html",
    "https://pages.nist.gov/ACVP/draft-celi-acvp-ml-dsa.html",
]

ACVP_SKELETON_SESSION_STORE: Dict[str, Dict[str, Any]] = {}
ACVP_SKELETON_VECTOR_SET_STORE: Dict[str, Dict[str, Any]] = {}

_HEX_RE = re.compile(r"^[0-9A-Fa-f]+$")
VECTOR_GENERATION_AVAILABLE_ACTION = (
    "Server-side vector generation from negotiated capabilities is available in "
    "Phase 3-4; enable autoGenerateVectorSets or call /vectorSets/generate."
)


def with_skeleton_metadata(body: Dict[str, Any]) -> Dict[str, Any]:
    return {**body, **SKELETON_METADATA}


def acvp_skeleton_error(
    status_code: int,
    code: str,
    message: str,
    path: Optional[str] = None,
) -> JSONResponse:
    return JSONResponse(
        status_code=status_code,
        content=with_skeleton_metadata(
            {
                "error": {
                    "code": code,
                    "message": message,
                    "path": path,
                }
            }
        ),
    )


def version() -> Dict[str, Any]:
    return with_skeleton_metadata(
        {
            "acvVersion": "1.0",
            "apiVersion": "v1",
            "serverName": "FIPS204 ACVP Local Skeleton",
            "implementationPhase": "3-4",
            "nistReferences": NIST_REFERENCES,
        }
    )


def algorithms() -> Dict[str, Any]:
    return with_skeleton_metadata(
        {
            "algorithms": [
                {
                    "algorithm": "ML-DSA",
                    "revision": "FIPS204",
                    "modes": ["keyGen", "sigGen", "sigVer"],
                    "parameterSets": ["ML-DSA-44", "ML-DSA-65", "ML-DSA-87"],
                    "signatureInterfaces": ["internal", "external"],
                    "internal": {
                        "externalMu": [False, True],
                        "deterministic": [False, True],
                    },
                    "external": {
                        "preHash": ["pure", "preHash"],
                        "context": True,
                        "hashAlgs": [
                            "SHA2-224",
                            "SHA2-256",
                            "SHA2-384",
                            "SHA2-512",
                            "SHA2-512/224",
                            "SHA2-512/256",
                            "SHA3-224",
                            "SHA3-256",
                            "SHA3-384",
                            "SHA3-512",
                        ],
                    },
                    "localOracleLimitations": [
                        "SHAKE-128 and SHAKE-256 are accepted by the schema but not generated by the local Python preHash oracle because this API does not carry SHAKE output length.",
                        "Phase 3-4 supports deterministic local-fips204-skeleton vector generation from negotiated capabilities; production vector generation is not implemented.",
                        "Production auth/JWT/mTLS is not implemented.",
                        "DB persistence is not implemented.",
                    ],
                    "nistReferences": NIST_REFERENCES,
                }
            ]
        }
    )


def list_test_sessions() -> Dict[str, Any]:
    return with_skeleton_metadata(
        {
            "testSessions": [
                _session_summary(session)
                for session in ACVP_SKELETON_SESSION_STORE.values()
            ]
        }
    )


def create_test_session(payload: AcvpV1TestSessionCreateRequest) -> Any:
    if payload.prompt is not None and payload.algorithms is not None:
        return acvp_skeleton_error(
            400,
            "INVALID_REQUEST",
            "prompt and algorithms cannot both be present in one test session request.",
            "$",
        )
    if payload.algorithms is not None:
        return _create_registration_session(payload)
    if payload.prompt is None:
        return acvp_skeleton_error(
            400,
            "INVALID_REQUEST",
            "Request must include either prompt or algorithms.",
            "$",
        )

    try:
        prompt_vs = validate_mldsa_vector_set(payload.prompt)
        expected_results = None
        status = "created"
        vector_status = "created"
        if payload.autoGenerateExpectedResults:
            expected_results = generate_expected_results_from_prompt(payload.prompt)
            validate_mldsa_response(expected_results, expected_mode=prompt_vs["mode"])
            status = "vectorReady"
            vector_status = "ready"
    except AcvpSchemaError as exc:
        return acvp_skeleton_error(400, exc.code, exc.message, exc.path)
    except MldsaOracleInputError as exc:
        return acvp_skeleton_error(400, "ORACLE_INPUT_ERROR", str(exc), "$")
    except MldsaOracleError as exc:
        return acvp_skeleton_error(500, "ORACLE_EXECUTION_ERROR", str(exc), "$")

    now = _timestamp()
    session_id = str(uuid4())
    vector_set_id = str(uuid4())
    vector_set_url = f"/acvp/v1/vectorSets/{vector_set_id}"

    session = {
        "testSessionId": session_id,
        "createdAt": now,
        "updatedAt": now,
        "status": status,
        "label": payload.label,
        "vectorSetIds": [vector_set_id],
        "vectorSetUrls": [vector_set_url],
        **SKELETON_METADATA,
    }
    vector_set = {
        "vectorSetId": vector_set_id,
        "testSessionId": session_id,
        "createdAt": now,
        "updatedAt": now,
        "status": vector_status,
        "prompt": payload.prompt,
        "expectedResults": expected_results,
        "response": None,
        "validationResult": None,
        "report": None,
        **SKELETON_METADATA,
    }
    ACVP_SKELETON_SESSION_STORE[session_id] = session
    ACVP_SKELETON_VECTOR_SET_STORE[vector_set_id] = vector_set

    return with_skeleton_metadata(
        {
            "testSessionId": session_id,
            "status": status,
            "label": payload.label,
            "vectorSetUrls": [vector_set_url],
            "vectorSetIds": [vector_set_id],
            "createdAt": now,
            "updatedAt": now,
        }
    )


def _create_registration_session(payload: AcvpV1TestSessionCreateRequest) -> Any:
    try:
        container_payload: Dict[str, Any] = {"algorithms": payload.algorithms}
        if payload.label is not None:
            container_payload["label"] = payload.label
        if payload.metadata is not None:
            container_payload["metadata"] = payload.metadata
        registration_container = validate_registration_container(container_payload)
        negotiated_capabilities = negotiate_mldsa_capabilities(registration_container)
        campaign_seed = _resolve_campaign_seed(payload.campaignSeed, registration_container)
        tests_per_group = _resolve_tests_per_group(payload.testsPerGroup)
    except AcvpSchemaError as exc:
        return acvp_skeleton_error(400, exc.code, exc.message, exc.path)

    now = _timestamp()
    session_id = str(uuid4())
    session = {
        "testSessionId": session_id,
        "createdAt": now,
        "updatedAt": now,
        "status": "capabilitiesAccepted",
        "label": payload.label,
        "registration": registration_container,
        "negotiatedCapabilities": negotiated_capabilities,
        "negotiationWarnings": negotiated_capabilities["warnings"],
        "unsupported": negotiated_capabilities["unsupported"],
        "campaignSeed": campaign_seed,
        "testsPerGroup": tests_per_group,
        "vectorSetIds": [],
        "vectorSetUrls": [],
        "nextAction": VECTOR_GENERATION_AVAILABLE_ACTION,
        **SKELETON_METADATA,
    }
    ACVP_SKELETON_SESSION_STORE[session_id] = session

    if payload.autoGenerateVectorSets:
        generated = _generate_and_store_vector_sets(
            session,
            campaign_seed=campaign_seed,
            tests_per_group=tests_per_group,
        )
        if isinstance(generated, JSONResponse):
            ACVP_SKELETON_SESSION_STORE.pop(session_id, None)
            return generated
        return _registration_session_response(session)

    return _registration_session_response(session)


def generate_vector_sets_for_session(
    session_id: str,
    payload: AcvpV1VectorSetGenerateRequest,
) -> Any:
    session = _get_session(session_id)
    if isinstance(session, JSONResponse):
        return session
    if "negotiatedCapabilities" not in session:
        return acvp_skeleton_error(
            409,
            "NEGOTIATED_CAPABILITIES_NOT_AVAILABLE",
            "This test session was not created from a registration container.",
            f"/acvp/v1/testSessions/{session_id}/vectorSets/generate",
        )
    if session["vectorSetIds"]:
        return acvp_skeleton_error(
            409,
            "VECTOR_SETS_ALREADY_GENERATED",
            "Vector sets have already been generated for this test session.",
            f"/acvp/v1/testSessions/{session_id}/vectorSets/generate",
        )

    try:
        campaign_seed = _resolve_campaign_seed(
            payload.campaignSeed or session.get("campaignSeed"),
            session["registration"],
        )
        tests_per_group = _resolve_tests_per_group(
            payload.testsPerGroup or session.get("testsPerGroup")
        )
    except AcvpSchemaError as exc:
        return acvp_skeleton_error(400, exc.code, exc.message, exc.path)

    generated = _generate_and_store_vector_sets(
        session,
        campaign_seed=campaign_seed,
        tests_per_group=tests_per_group,
    )
    if isinstance(generated, JSONResponse):
        return generated
    return _registration_session_response(session)


def _registration_session_response(session: Dict[str, Any]) -> Dict[str, Any]:
    response = {
        "testSessionId": session["testSessionId"],
        "status": session["status"],
        "label": session.get("label"),
        "negotiatedCapabilities": session["negotiatedCapabilities"],
        "negotiationWarnings": session["negotiationWarnings"],
        "unsupported": session["unsupported"],
        "vectorSetIds": list(session["vectorSetIds"]),
        "vectorSetUrls": list(session["vectorSetUrls"]),
        "createdAt": session["createdAt"],
        "updatedAt": session["updatedAt"],
    }
    if "vectorGeneration" in session:
        response["vectorGeneration"] = session["vectorGeneration"]
    else:
        response["nextAction"] = VECTOR_GENERATION_AVAILABLE_ACTION
    return with_skeleton_metadata(response)


def _generate_and_store_vector_sets(
    session: Dict[str, Any],
    *,
    campaign_seed: str,
    tests_per_group: int,
) -> Optional[JSONResponse]:
    try:
        prompts = generate_vector_sets_from_negotiated_capabilities(
            session["negotiatedCapabilities"],
            campaign_seed=campaign_seed,
            tests_per_group=tests_per_group,
        )
        prepared = _prepare_generated_vector_sets(
            session["testSessionId"],
            prompts,
            campaign_seed,
        )
    except AcvpSchemaError as exc:
        return acvp_skeleton_error(500, exc.code, exc.message, exc.path)
    except MldsaOracleInputError as exc:
        return acvp_skeleton_error(400, "ORACLE_INPUT_ERROR", str(exc), "$")
    except MldsaOracleError as exc:
        return acvp_skeleton_error(500, "ORACLE_EXECUTION_ERROR", str(exc), "$")
    except ValueError as exc:
        return acvp_skeleton_error(500, "VECTOR_GENERATION_ERROR", str(exc), "$")

    vector_set_ids: List[str] = []
    vector_set_urls: List[str] = []
    now = _timestamp()
    for vector_set in prepared:
        vector_set["createdAt"] = now
        vector_set["updatedAt"] = now
        ACVP_SKELETON_VECTOR_SET_STORE[vector_set["vectorSetId"]] = vector_set
        vector_set_ids.append(vector_set["vectorSetId"])
        vector_set_urls.append(f"/acvp/v1/vectorSets/{vector_set['vectorSetId']}")

    session["status"] = "vectorReady"
    session["updatedAt"] = now
    session["campaignSeed"] = campaign_seed
    session["testsPerGroup"] = tests_per_group
    session["vectorSetIds"] = vector_set_ids
    session["vectorSetUrls"] = vector_set_urls
    session["nextAction"] = "Download vector sets and submit results."
    session["vectorGeneration"] = {
        "campaignSeed": campaign_seed,
        "testsPerGroup": tests_per_group,
        "generatedVectorSetCount": len(vector_set_ids),
        "modes": [
            normalize_acvp_json(vector_set["prompt"])["mode"]
            for vector_set in prepared
        ],
        "generationProfile": GENERATION_PROFILE,
        "localSkeletonBehavior": True,
    }
    return None


def _prepare_generated_vector_sets(
    session_id: str,
    prompts: List[Dict[str, Any]],
    campaign_seed: str,
) -> List[Dict[str, Any]]:
    prepared: List[Dict[str, Any]] = []
    for prompt in prompts:
        prompt_vs = validate_mldsa_vector_set(prompt)
        expected_results = generate_expected_results_from_prompt(prompt)
        validate_mldsa_response(expected_results, expected_mode=prompt_vs["mode"])
        vector_set_id = str(uuid4())
        prepared.append(
            {
                "vectorSetId": vector_set_id,
                "testSessionId": session_id,
                "status": "ready",
                "prompt": prompt,
                "expectedResults": expected_results,
                "response": None,
                "validationResult": None,
                "report": None,
                "generatedFromCapabilities": True,
                "mode": prompt_vs["mode"],
                "vsId": prompt_vs["vsId"],
                "campaignSeed": campaign_seed,
                "generationProfile": GENERATION_PROFILE,
                **SKELETON_METADATA,
            }
        )
    return prepared


def _resolve_campaign_seed(
    provided_seed: Optional[str],
    registration_container: Dict[str, Any],
) -> str:
    if provided_seed is None:
        return fallback_campaign_seed(registration_container)
    if not isinstance(provided_seed, str):
        raise AcvpSchemaError("invalid_type", "campaignSeed must be a hex string", "$.campaignSeed")
    if len(provided_seed) % 2 != 0 or _HEX_RE.fullmatch(provided_seed) is None:
        raise AcvpSchemaError("invalid_hex", "campaignSeed must be an even-length hex string", "$.campaignSeed")
    byte_len = len(provided_seed) // 2
    if byte_len < 16 or byte_len > 64:
        raise AcvpSchemaError(
            "invalid_value",
            "campaignSeed must be between 16 and 64 bytes",
            "$.campaignSeed",
        )
    return provided_seed.upper()


def _resolve_tests_per_group(value: Optional[int]) -> int:
    if value is None:
        return DEFAULT_TESTS_PER_GROUP
    if not isinstance(value, int) or isinstance(value, bool):
        raise AcvpSchemaError("invalid_type", "testsPerGroup must be an integer", "$.testsPerGroup")
    if value < 1 or value > MAX_TESTS_PER_GROUP:
        raise AcvpSchemaError(
            "invalid_value",
            f"testsPerGroup must be between 1 and {MAX_TESTS_PER_GROUP}",
            "$.testsPerGroup",
        )
    return value


def get_test_session(session_id: str) -> Any:
    session = _get_session(session_id)
    if isinstance(session, JSONResponse):
        return session

    return with_skeleton_metadata(
        {
            **_session_summary(session),
            "vectorSets": [
                _vector_set_summary(ACVP_SKELETON_VECTOR_SET_STORE[vector_set_id])
                for vector_set_id in session["vectorSetIds"]
                if vector_set_id in ACVP_SKELETON_VECTOR_SET_STORE
            ],
        }
    )


def get_test_session_vector_sets(session_id: str) -> Any:
    session = _get_session(session_id)
    if isinstance(session, JSONResponse):
        return session

    return with_skeleton_metadata(
        {
            "testSessionId": session_id,
            "vectorSets": [
                _vector_set_summary(ACVP_SKELETON_VECTOR_SET_STORE[vector_set_id])
                for vector_set_id in session["vectorSetIds"]
                if vector_set_id in ACVP_SKELETON_VECTOR_SET_STORE
            ],
            **(
                {"nextAction": VECTOR_GENERATION_AVAILABLE_ACTION}
                if not session["vectorSetIds"]
                and session["status"] == "capabilitiesAccepted"
                else {}
            ),
        }
    )


def get_vector_set(vector_set_id: str) -> Any:
    vector_set = _get_vector_set(vector_set_id)
    if isinstance(vector_set, JSONResponse):
        return vector_set

    return with_skeleton_metadata(
        {
            "vectorSetId": vector_set_id,
            "testSessionId": vector_set["testSessionId"],
            "status": vector_set["status"],
            "prompt": vector_set["prompt"],
            "generatedFromCapabilities": vector_set.get("generatedFromCapabilities", False),
            "generationProfile": vector_set.get("generationProfile"),
            "campaignSeed": vector_set.get("campaignSeed"),
        }
    )


def get_vector_set_expected_results(vector_set_id: str) -> Any:
    vector_set = _get_vector_set(vector_set_id)
    if isinstance(vector_set, JSONResponse):
        return vector_set
    if vector_set["expectedResults"] is None:
        return acvp_skeleton_error(
            409,
            "EXPECTED_RESULTS_NOT_READY",
            "Expected results are not available for this local skeleton vector set.",
            f"/acvp/v1/vectorSets/{vector_set_id}/expectedResults",
        )

    return with_skeleton_metadata(
        {
            "vectorSetId": vector_set_id,
            "testSessionId": vector_set["testSessionId"],
            "expectedResults": vector_set["expectedResults"],
        }
    )


def submit_vector_set_results(vector_set_id: str, response: Any) -> Any:
    vector_set = _get_vector_set(vector_set_id)
    if isinstance(vector_set, JSONResponse):
        return vector_set
    if vector_set["status"] not in {"ready", "resultsSubmitted", "validated", "failed"}:
        return acvp_skeleton_error(
            409,
            "VECTOR_SET_NOT_READY",
            "Vector set is not ready for result submission.",
            f"/acvp/v1/vectorSets/{vector_set_id}/results",
        )
    if vector_set["expectedResults"] is None:
        return acvp_skeleton_error(
            409,
            "EXPECTED_RESULTS_NOT_READY",
            "Expected results must be generated before result submission in the local skeleton.",
            f"/acvp/v1/vectorSets/{vector_set_id}/results",
        )

    mode = normalize_acvp_json(vector_set["prompt"]).get("mode")
    try:
        validate_mldsa_response(response, expected_mode=mode)
        bundle = {
            "prompt": vector_set["prompt"],
            "expectedResults": vector_set["expectedResults"],
            "response": response,
            "label": _get_session_label(vector_set["testSessionId"]),
        }
        validation_result = validate(bundle)
        report = build_report(vector_set_id, validation_result)
    except AcvpSchemaError as exc:
        return acvp_skeleton_error(400, exc.code, exc.message, exc.path)
    except ValueError as exc:
        return acvp_skeleton_error(400, "VALIDATION_ERROR", str(exc), "$")

    passed = _validation_passed(validation_result)
    now = _timestamp()
    vector_set["response"] = response
    vector_set["validationResult"] = validation_result
    vector_set["report"] = report
    vector_set["status"] = "validated" if passed else "failed"
    vector_set["updatedAt"] = now

    session = ACVP_SKELETON_SESSION_STORE.get(vector_set["testSessionId"])
    if session is not None:
        session["status"] = "validated" if passed else "failed"
        session["updatedAt"] = now

    return with_skeleton_metadata(
        {
            "vectorSetId": vector_set_id,
            "testSessionId": vector_set["testSessionId"],
            "status": vector_set["status"],
            "validationResult": validation_result,
            "report": report,
        }
    )


def get_vector_set_results(vector_set_id: str) -> Any:
    vector_set = _get_vector_set(vector_set_id)
    if isinstance(vector_set, JSONResponse):
        return vector_set
    if vector_set["validationResult"] is None:
        return acvp_skeleton_error(
            409,
            "RESULTS_NOT_SUBMITTED",
            "Results have not been submitted for this vector set.",
            f"/acvp/v1/vectorSets/{vector_set_id}/results",
        )

    return with_skeleton_metadata(
        {
            "vectorSetId": vector_set_id,
            "testSessionId": vector_set["testSessionId"],
            "status": vector_set["status"],
            "validationResult": vector_set["validationResult"],
            "report": vector_set["report"],
        }
    )


def get_test_session_results(session_id: str) -> Any:
    session = _get_session(session_id)
    if isinstance(session, JSONResponse):
        return session
    if not session["vectorSetIds"] and session["status"] == "capabilitiesAccepted":
        return acvp_skeleton_error(
            409,
            "VECTOR_SETS_NOT_GENERATED",
            "This registration session has no vector sets yet. Vector generation is planned for Phase 3-4.",
            f"/acvp/v1/testSessions/{session_id}/results",
        )

    vector_results = []
    for vector_set_id in session["vectorSetIds"]:
        vector_set = ACVP_SKELETON_VECTOR_SET_STORE.get(vector_set_id)
        if vector_set is None or vector_set["validationResult"] is None:
            continue
        vector_results.append(
            {
                "vectorSetId": vector_set_id,
                "status": vector_set["status"],
                "validationResult": vector_set["validationResult"],
                "report": vector_set["report"],
            }
        )

    if not vector_results:
        return acvp_skeleton_error(
            409,
            "RESULTS_NOT_SUBMITTED",
            "No vector set results have been submitted for this test session.",
            f"/acvp/v1/testSessions/{session_id}/results",
        )

    return with_skeleton_metadata(
        {
            "testSessionId": session_id,
            "status": session["status"],
            "summary": {
                "totalVectorSets": len(session["vectorSetIds"]),
                "submittedVectorSets": len(vector_results),
                "passedVectorSets": sum(
                    1
                    for item in vector_results
                    if item["status"] == "validated"
                ),
                "failedVectorSets": sum(
                    1
                    for item in vector_results
                    if item["status"] == "failed"
                ),
            },
            "vectorSetResults": vector_results,
        }
    )


def delete_test_session(session_id: str) -> Any:
    session = _get_session(session_id)
    if isinstance(session, JSONResponse):
        return session

    for vector_set_id in list(session["vectorSetIds"]):
        ACVP_SKELETON_VECTOR_SET_STORE.pop(vector_set_id, None)
    del ACVP_SKELETON_SESSION_STORE[session_id]

    return with_skeleton_metadata(
        {
            "deleted": True,
            "testSessionId": session_id,
            "status": "cancelled",
            "localSkeletonBehavior": True,
        }
    )


def _get_session(session_id: str) -> Any:
    session = ACVP_SKELETON_SESSION_STORE.get(session_id)
    if session is None:
        return acvp_skeleton_error(
            404,
            "UNKNOWN_TEST_SESSION",
            "Unknown testSessionId.",
            f"/acvp/v1/testSessions/{session_id}",
        )
    return session


def _get_vector_set(vector_set_id: str) -> Any:
    vector_set = ACVP_SKELETON_VECTOR_SET_STORE.get(vector_set_id)
    if vector_set is None:
        return acvp_skeleton_error(
            404,
            "UNKNOWN_VECTOR_SET",
            "Unknown vectorSetId.",
            f"/acvp/v1/vectorSets/{vector_set_id}",
        )
    return vector_set


def _session_summary(session: Dict[str, Any]) -> Dict[str, Any]:
    vector_set_summaries = [
        _vector_set_summary(ACVP_SKELETON_VECTOR_SET_STORE[vector_set_id])
        for vector_set_id in session["vectorSetIds"]
        if vector_set_id in ACVP_SKELETON_VECTOR_SET_STORE
    ]
    first_summary = vector_set_summaries[0] if vector_set_summaries else {}
    summary = {
        "testSessionId": session["testSessionId"],
        "createdAt": session["createdAt"],
        "updatedAt": session["updatedAt"],
        "status": session["status"],
        "label": session.get("label"),
        "vectorSetIds": list(session["vectorSetIds"]),
        "vectorSetUrls": list(session["vectorSetUrls"]),
        "vectorSetCount": len(session["vectorSetIds"]),
        "algorithm": first_summary.get("algorithm"),
        "mode": first_summary.get("mode"),
        "revision": first_summary.get("revision"),
        "testGroupCount": first_summary.get("testGroupCount", 0),
        "testCaseCount": first_summary.get("testCaseCount", 0),
        **SKELETON_METADATA,
    }
    if "negotiatedCapabilities" in session:
        summary["negotiatedCapabilities"] = session["negotiatedCapabilities"]
        summary["negotiationWarnings"] = session.get("negotiationWarnings", [])
        summary["unsupported"] = session.get("unsupported", [])
        summary["nextAction"] = session.get("nextAction", VECTOR_GENERATION_AVAILABLE_ACTION)
    if "vectorGeneration" in session:
        summary["vectorGeneration"] = session["vectorGeneration"]
    return summary


def _vector_set_summary(vector_set: Dict[str, Any]) -> Dict[str, Any]:
    prompt_summary = summarize_vector_set(normalize_acvp_json(vector_set["prompt"]))
    return {
        "vectorSetId": vector_set["vectorSetId"],
        "testSessionId": vector_set["testSessionId"],
        "status": vector_set["status"],
        "url": f"/acvp/v1/vectorSets/{vector_set['vectorSetId']}",
        "generatedFromCapabilities": vector_set.get("generatedFromCapabilities", False),
        "generationProfile": vector_set.get("generationProfile"),
        "campaignSeed": vector_set.get("campaignSeed"),
        **prompt_summary,
        **SKELETON_METADATA,
    }


def _get_session_label(session_id: str) -> Optional[str]:
    session = ACVP_SKELETON_SESSION_STORE.get(session_id)
    if session is None:
        return None
    label = session.get("label")
    return str(label) if label is not None else None


def _validation_passed(validation_result: Dict[str, Any]) -> bool:
    summary = validation_result["summary"]
    return (
        summary["failed"] == 0
        and summary["missing"] == 0
        and summary["malformed"] == 0
        and summary.get("extra", 0) == 0
    )


def _timestamp() -> str:
    return datetime.now(timezone.utc).isoformat()
