from __future__ import annotations

from datetime import datetime, timedelta, timezone
import re
from typing import Any, Dict, List, Optional
from uuid import uuid4

from fastapi.responses import JSONResponse

from ..acvp_mldsa.errors import AcvpSchemaError
from ..acvp_mldsa.expected import generate_expected_results_from_prompt
from ..acvp_mldsa.validators import validate_mldsa_response, validate_mldsa_vector_set
from ..acvp_parser import normalize_acvp_json, summarize_vector_set
from ..crypto_oracle.mldsa_errors import MldsaOracleError, MldsaOracleInputError
from ..models import AcvpV1TestSessionCreateRequest, AcvpV1VectorSetGenerateRequest
from ..report import build_report
from ..validator import validate
from .capabilities import (
    negotiate_mldsa_capabilities,
    validate_registration_container,
)
from .vector_generation import (
    DEFAULT_TESTS_PER_GROUP,
    GENERATION_PROFILE,
    MAX_TESTS_PER_GROUP,
    fallback_campaign_seed,
    generate_vector_sets_from_negotiated_capabilities,
)
from .state_machine import (
    StateTransitionError,
    TestSessionStatus,
    VectorSetStatus,
    add_state_event,
    is_terminal_status,
    now_timestamp,
    session_is_expired,
    transition_session,
    transition_vector_set,
    vector_set_is_expired,
)


SKELETON_PROFILE = "local-fips204-skeleton"
SKELETON_METADATA: Dict[str, Any] = {
    "productionReady": False,
    "profile": SKELETON_PROFILE,
    "demoOnly": True,
    "notProductionAcvp": True,
}

NIST_REFERENCES = [
    "https://pages.nist.gov/ACVP/draft-fussell-acvp-spec.html",
    "https://pages.nist.gov/ACVP/draft-celi-acvp-ml-dsa.html",
    "https://csrc.nist.gov/pubs/fips/204/final",
]

ACVP_SKELETON_SESSION_STORE: Dict[str, Dict[str, Any]] = {}
ACVP_SKELETON_VECTOR_SET_STORE: Dict[str, Dict[str, Any]] = {}

_HEX_RE = re.compile(r"^[0-9A-Fa-f]+$")
VECTOR_GENERATION_AVAILABLE_ACTION = (
    "Server-side vector generation from negotiated capabilities is available in "
    "Phase 3-5; enable autoGenerateVectorSets or call /vectorSets/generate."
)


def with_skeleton_metadata(body: Dict[str, Any]) -> Dict[str, Any]:
    return {**body, **SKELETON_METADATA}


def acvp_skeleton_error(
    status_code: int,
    code: str,
    message: str,
    path: Optional[str] = None,
) -> JSONResponse:
    return JSONResponse(
        status_code=status_code,
        content=with_skeleton_metadata(
            {
                "error": {
                    "code": code,
                    "message": message,
                    "path": path,
                }
            }
        ),
    )


def version() -> Dict[str, Any]:
    return with_skeleton_metadata(
        {
            "acvVersion": "1.0",
            "apiVersion": "v1",
            "serverName": "FIPS204 ACVP Local Skeleton",
            "implementationPhase": "3-5",
            "nistReferences": NIST_REFERENCES,
        }
    )


def algorithms() -> Dict[str, Any]:
    return with_skeleton_metadata(
        {
            "algorithms": [
                {
                    "algorithm": "ML-DSA",
                    "revision": "FIPS204",
                    "modes": ["keyGen", "sigGen", "sigVer"],
                    "parameterSets": ["ML-DSA-44", "ML-DSA-65", "ML-DSA-87"],
                    "signatureInterfaces": ["internal", "external"],
                    "internal": {
                        "externalMu": [False, True],
                        "deterministic": [False, True],
                    },
                    "external": {
                        "preHash": ["pure", "preHash"],
                        "context": True,
                        "hashAlgs": [
                            "SHA2-224",
                            "SHA2-256",
                            "SHA2-384",
                            "SHA2-512",
                            "SHA2-512/224",
                            "SHA2-512/256",
                            "SHA3-224",
                            "SHA3-256",
                            "SHA3-384",
                            "SHA3-512",
                        ],
                    },
                    "localOracleLimitations": [
                        "SHAKE-128 and SHAKE-256 are accepted by the schema but not generated by the local Python preHash oracle because this API does not carry SHAKE output length.",
                        "Phase 3-5 supports deterministic local-fips204-skeleton vector generation and a local state machine; production vector generation is not implemented.",
                        "Production auth/JWT/mTLS is not implemented.",
                        "DB persistence is not implemented.",
                    ],
                    "nistReferences": NIST_REFERENCES,
                }
            ]
        }
    )


def list_test_sessions(status: Optional[str] = None) -> Dict[str, Any]:
    sessions = list(ACVP_SKELETON_SESSION_STORE.values())
    if status is not None:
        sessions = [session for session in sessions if session.get("status") == status]
    return with_skeleton_metadata(
        {
            "testSessions": [
                _session_summary(session)
                for session in sessions
            ],
            "query": {"status": status} if status is not None else {},
        }
    )


def create_test_session(payload: AcvpV1TestSessionCreateRequest) -> Any:
    if payload.prompt is not None and payload.algorithms is not None:
        return acvp_skeleton_error(
            400,
            "INVALID_REQUEST",
            "prompt and algorithms cannot both be present in one test session request.",
            "$",
        )
    if payload.algorithms is not None:
        return _create_registration_session(payload)
    if payload.prompt is None:
        return acvp_skeleton_error(
            400,
            "INVALID_REQUEST",
            "Request must include either prompt or algorithms.",
            "$",
        )

    try:
        prompt_vs = validate_mldsa_vector_set(payload.prompt)
        expected_results = None
        if payload.autoGenerateExpectedResults:
            expected_results = generate_expected_results_from_prompt(payload.prompt)
            validate_mldsa_response(expected_results, expected_mode=prompt_vs["mode"])
    except AcvpSchemaError as exc:
        return acvp_skeleton_error(400, exc.code, exc.message, exc.path)
    except MldsaOracleInputError as exc:
        return acvp_skeleton_error(400, "ORACLE_INPUT_ERROR", str(exc), "$")
    except MldsaOracleError as exc:
        return acvp_skeleton_error(500, "ORACLE_EXECUTION_ERROR", str(exc), "$")

    now = _timestamp()
    session_id = str(uuid4())
    vector_set_id = str(uuid4())
    vector_set_url = f"/acvp/v1/vectorSets/{vector_set_id}"
    expires_at = _expires_at_from_seconds(payload.expiresInSeconds)

    session = {
        "testSessionId": session_id,
        "createdAt": now,
        "updatedAt": now,
        "status": TestSessionStatus.CREATED.value,
        "label": payload.label,
        "expiresAt": expires_at,
        "vectorSetIds": [vector_set_id],
        "vectorSetUrls": [vector_set_url],
        **SKELETON_METADATA,
    }
    vector_set = {
        "vectorSetId": vector_set_id,
        "testSessionId": session_id,
        "createdAt": now,
        "updatedAt": now,
        "status": VectorSetStatus.CREATED.value,
        "expiresAt": expires_at,
        "prompt": payload.prompt,
        "expectedResults": expected_results,
        "response": None,
        "validationResult": None,
        "report": None,
        "mode": prompt_vs["mode"],
        "vsId": prompt_vs["vsId"],
        **SKELETON_METADATA,
    }
    _record_created(session, TestSessionStatus.CREATED.value, "Prompt-based test session created.")
    _record_created(vector_set, VectorSetStatus.CREATED.value, "Prompt-based vector set created.")
    if expected_results is not None:
        transition_vector_set(
            vector_set,
            VectorSetStatus.READY.value,
            reason="Expected results generated for prompt-based vector set.",
        )
        transition_session(
            session,
            TestSessionStatus.VECTOR_READY.value,
            reason="Prompt-based vector set is ready for download.",
        )
    ACVP_SKELETON_SESSION_STORE[session_id] = session
    ACVP_SKELETON_VECTOR_SET_STORE[vector_set_id] = vector_set

    return with_skeleton_metadata(
        {
            "testSessionId": session_id,
            "status": session["status"],
            "label": payload.label,
            "vectorSetUrls": [vector_set_url],
            "vectorSetIds": [vector_set_id],
            "createdAt": now,
            "updatedAt": session["updatedAt"],
            "expiresAt": expires_at,
            "stateHistory": list(session["stateHistory"]),
        }
    )


def _create_registration_session(payload: AcvpV1TestSessionCreateRequest) -> Any:
    try:
        container_payload: Dict[str, Any] = {"algorithms": payload.algorithms}
        if payload.label is not None:
            container_payload["label"] = payload.label
        if payload.metadata is not None:
            container_payload["metadata"] = payload.metadata
        registration_container = validate_registration_container(container_payload)
        negotiated_capabilities = negotiate_mldsa_capabilities(registration_container)
        campaign_seed = _resolve_campaign_seed(payload.campaignSeed, registration_container)
        tests_per_group = _resolve_tests_per_group(payload.testsPerGroup)
    except AcvpSchemaError as exc:
        return acvp_skeleton_error(400, exc.code, exc.message, exc.path)

    now = _timestamp()
    session_id = str(uuid4())
    expires_at = _expires_at_from_seconds(payload.expiresInSeconds)
    session = {
        "testSessionId": session_id,
        "createdAt": now,
        "updatedAt": now,
        "status": TestSessionStatus.CREATED.value,
        "label": payload.label,
        "expiresAt": expires_at,
        "registration": registration_container,
        "negotiatedCapabilities": negotiated_capabilities,
        "negotiationWarnings": negotiated_capabilities["warnings"],
        "unsupported": negotiated_capabilities["unsupported"],
        "campaignSeed": campaign_seed,
        "testsPerGroup": tests_per_group,
        "vectorSetIds": [],
        "vectorSetUrls": [],
        "nextAction": VECTOR_GENERATION_AVAILABLE_ACTION,
        **SKELETON_METADATA,
    }
    _record_created(session, TestSessionStatus.CREATED.value, "Registration test session created.")
    transition_session(
        session,
        TestSessionStatus.CAPABILITIES_ACCEPTED.value,
        reason="ML-DSA capabilities accepted by local skeleton negotiation.",
    )
    ACVP_SKELETON_SESSION_STORE[session_id] = session

    if payload.autoGenerateVectorSets:
        generated = _generate_and_store_vector_sets(
            session,
            campaign_seed=campaign_seed,
            tests_per_group=tests_per_group,
            expires_at=expires_at,
            reason="Registration requested autoGenerateVectorSets.",
        )
        if isinstance(generated, JSONResponse):
            ACVP_SKELETON_SESSION_STORE.pop(session_id, None)
            return generated
        return _registration_session_response(session)

    return _registration_session_response(session)


def generate_vector_sets_for_session(
    session_id: str,
    payload: AcvpV1VectorSetGenerateRequest,
) -> Any:
    session = _get_session(session_id)
    if isinstance(session, JSONResponse):
        return session
    path = f"/acvp/v1/testSessions/{session_id}/vectorSets/generate"
    unavailable = _reject_if_session_unavailable(session, path)
    if isinstance(unavailable, JSONResponse):
        return unavailable
    if "negotiatedCapabilities" not in session:
        return acvp_skeleton_error(
            409,
            "NEGOTIATED_CAPABILITIES_NOT_AVAILABLE",
            "This test session was not created from a registration container.",
            path,
        )
    if session["vectorSetIds"]:
        return acvp_skeleton_error(
            409,
            "VECTOR_SETS_ALREADY_GENERATED",
            "Vector sets have already been generated for this test session.",
            path,
        )
    if session["status"] != TestSessionStatus.CAPABILITIES_ACCEPTED.value:
        return acvp_skeleton_error(
            409,
            "INVALID_SESSION_STATE",
            "Vector sets can only be generated for a capabilitiesAccepted session.",
            path,
        )

    try:
        campaign_seed = _resolve_campaign_seed(
            payload.campaignSeed or session.get("campaignSeed"),
            session["registration"],
        )
        tests_per_group = _resolve_tests_per_group(
            payload.testsPerGroup or session.get("testsPerGroup")
        )
    except AcvpSchemaError as exc:
        return acvp_skeleton_error(400, exc.code, exc.message, exc.path)

    generated = _generate_and_store_vector_sets(
        session,
        campaign_seed=campaign_seed,
        tests_per_group=tests_per_group,
        expires_at=_expires_at_from_seconds(payload.expiresInSeconds) or session.get("expiresAt"),
        reason="Explicit vector generation endpoint called.",
    )
    if isinstance(generated, JSONResponse):
        return generated
    return _registration_session_response(session)


def _registration_session_response(session: Dict[str, Any]) -> Dict[str, Any]:
    response = {
        "testSessionId": session["testSessionId"],
        "status": session["status"],
        "label": session.get("label"),
        "negotiatedCapabilities": session["negotiatedCapabilities"],
        "negotiationWarnings": session["negotiationWarnings"],
        "unsupported": session["unsupported"],
        "vectorSetIds": list(session["vectorSetIds"]),
        "vectorSetUrls": list(session["vectorSetUrls"]),
        "createdAt": session["createdAt"],
        "updatedAt": session["updatedAt"],
        "expiresAt": session.get("expiresAt"),
        "stateHistory": list(session.get("stateHistory", [])),
    }
    if "vectorGeneration" in session:
        response["vectorGeneration"] = session["vectorGeneration"]
    else:
        response["nextAction"] = VECTOR_GENERATION_AVAILABLE_ACTION
    return with_skeleton_metadata(response)


def _generate_and_store_vector_sets(
    session: Dict[str, Any],
    *,
    campaign_seed: str,
    tests_per_group: int,
    expires_at: Optional[str],
    reason: str,
) -> Optional[JSONResponse]:
    try:
        prompts = generate_vector_sets_from_negotiated_capabilities(
            session["negotiatedCapabilities"],
            campaign_seed=campaign_seed,
            tests_per_group=tests_per_group,
        )
        prepared = _prepare_generated_vector_sets(
            session["testSessionId"],
            prompts,
            campaign_seed,
        )
    except AcvpSchemaError as exc:
        return acvp_skeleton_error(500, exc.code, exc.message, exc.path)
    except MldsaOracleInputError as exc:
        return acvp_skeleton_error(400, "ORACLE_INPUT_ERROR", str(exc), "$")
    except MldsaOracleError as exc:
        return acvp_skeleton_error(500, "ORACLE_EXECUTION_ERROR", str(exc), "$")
    except ValueError as exc:
        return acvp_skeleton_error(500, "VECTOR_GENERATION_ERROR", str(exc), "$")

    vector_set_ids: List[str] = []
    vector_set_urls: List[str] = []
    now = _timestamp()
    for vector_set in prepared:
        vector_set["createdAt"] = now
        vector_set["updatedAt"] = now
        vector_set["expiresAt"] = expires_at
        _record_created(
            vector_set,
            VectorSetStatus.CREATED.value,
            "Vector set created from negotiated capabilities.",
        )
        transition_vector_set(
            vector_set,
            VectorSetStatus.READY.value,
            reason="Expected results generated for negotiated vector set.",
            metadata={"generationProfile": GENERATION_PROFILE},
        )
        ACVP_SKELETON_VECTOR_SET_STORE[vector_set["vectorSetId"]] = vector_set
        vector_set_ids.append(vector_set["vectorSetId"])
        vector_set_urls.append(f"/acvp/v1/vectorSets/{vector_set['vectorSetId']}")

    if expires_at is not None and session.get("expiresAt") is None:
        session["expiresAt"] = expires_at
    transition_session(
        session,
        TestSessionStatus.VECTOR_READY.value,
        reason=reason,
        metadata={"generatedVectorSetCount": len(vector_set_ids)},
    )
    add_state_event(
        session,
        event="vectorGenerated",
        from_status=session["status"],
        to_status=session["status"],
        reason="Vector sets generated from negotiated capabilities.",
        metadata={
            "campaignSeed": campaign_seed,
            "testsPerGroup": tests_per_group,
            "generatedVectorSetCount": len(vector_set_ids),
        },
    )
    session["campaignSeed"] = campaign_seed
    session["testsPerGroup"] = tests_per_group
    session["vectorSetIds"] = vector_set_ids
    session["vectorSetUrls"] = vector_set_urls
    session["nextAction"] = "Download vector sets and submit results."
    session["vectorGeneration"] = {
        "campaignSeed": campaign_seed,
        "testsPerGroup": tests_per_group,
        "generatedVectorSetCount": len(vector_set_ids),
        "modes": [
            normalize_acvp_json(vector_set["prompt"])["mode"]
            for vector_set in prepared
        ],
        "generationProfile": GENERATION_PROFILE,
        "localSkeletonBehavior": True,
    }
    return None


def _prepare_generated_vector_sets(
    session_id: str,
    prompts: List[Dict[str, Any]],
    campaign_seed: str,
) -> List[Dict[str, Any]]:
    prepared: List[Dict[str, Any]] = []
    for prompt in prompts:
        prompt_vs = validate_mldsa_vector_set(prompt)
        expected_results = generate_expected_results_from_prompt(prompt)
        validate_mldsa_response(expected_results, expected_mode=prompt_vs["mode"])
        vector_set_id = str(uuid4())
        prepared.append(
            {
                "vectorSetId": vector_set_id,
                "testSessionId": session_id,
                "status": VectorSetStatus.CREATED.value,
                "prompt": prompt,
                "expectedResults": expected_results,
                "response": None,
                "validationResult": None,
                "report": None,
                "generatedFromCapabilities": True,
                "mode": prompt_vs["mode"],
                "vsId": prompt_vs["vsId"],
                "campaignSeed": campaign_seed,
                "generationProfile": GENERATION_PROFILE,
                **SKELETON_METADATA,
            }
        )
    return prepared


def _resolve_campaign_seed(
    provided_seed: Optional[str],
    registration_container: Dict[str, Any],
) -> str:
    if provided_seed is None:
        return fallback_campaign_seed(registration_container)
    if not isinstance(provided_seed, str):
        raise AcvpSchemaError("invalid_type", "campaignSeed must be a hex string", "$.campaignSeed")
    if len(provided_seed) % 2 != 0 or _HEX_RE.fullmatch(provided_seed) is None:
        raise AcvpSchemaError("invalid_hex", "campaignSeed must be an even-length hex string", "$.campaignSeed")
    byte_len = len(provided_seed) // 2
    if byte_len < 16 or byte_len > 64:
        raise AcvpSchemaError(
            "invalid_value",
            "campaignSeed must be between 16 and 64 bytes",
            "$.campaignSeed",
        )
    return provided_seed.upper()


def _resolve_tests_per_group(value: Optional[int]) -> int:
    if value is None:
        return DEFAULT_TESTS_PER_GROUP
    if not isinstance(value, int) or isinstance(value, bool):
        raise AcvpSchemaError("invalid_type", "testsPerGroup must be an integer", "$.testsPerGroup")
    if value < 1 or value > MAX_TESTS_PER_GROUP:
        raise AcvpSchemaError(
            "invalid_value",
            f"testsPerGroup must be between 1 and {MAX_TESTS_PER_GROUP}",
            "$.testsPerGroup",
        )
    return value


def get_test_session(session_id: str) -> Any:
    session = _get_session(session_id)
    if isinstance(session, JSONResponse):
        return session
    _expire_session_if_needed(session)

    return with_skeleton_metadata(
        {
            **_session_summary(session),
            "vectorSets": [
                _vector_set_summary(ACVP_SKELETON_VECTOR_SET_STORE[vector_set_id])
                for vector_set_id in session["vectorSetIds"]
                if vector_set_id in ACVP_SKELETON_VECTOR_SET_STORE
            ],
        }
    )


def get_test_session_vector_sets(session_id: str) -> Any:
    session = _get_session(session_id)
    if isinstance(session, JSONResponse):
        return session
    _expire_session_if_needed(session)

    return with_skeleton_metadata(
        {
            "testSessionId": session_id,
            "vectorSets": [
                _vector_set_summary(ACVP_SKELETON_VECTOR_SET_STORE[vector_set_id])
                for vector_set_id in session["vectorSetIds"]
                if vector_set_id in ACVP_SKELETON_VECTOR_SET_STORE
            ],
            **(
                {"nextAction": VECTOR_GENERATION_AVAILABLE_ACTION}
                if not session["vectorSetIds"]
                and session["status"] == "capabilitiesAccepted"
                else {}
            ),
        }
    )


def get_vector_set(vector_set_id: str) -> Any:
    vector_set = _get_vector_set(vector_set_id)
    if isinstance(vector_set, JSONResponse):
        return vector_set
    path = f"/acvp/v1/vectorSets/{vector_set_id}"
    unavailable = _reject_if_vector_unavailable(vector_set, path)
    if isinstance(unavailable, JSONResponse):
        return unavailable
    if vector_set["status"] == VectorSetStatus.CREATED.value:
        return acvp_skeleton_error(
            409,
            "VECTOR_SET_NOT_READY",
            "Vector set is not ready for download.",
            path,
        )

    if vector_set["status"] == VectorSetStatus.READY.value:
        transition_vector_set(
            vector_set,
            VectorSetStatus.DOWNLOADED.value,
            reason="Vector set prompt downloaded.",
        )
        vector_set["downloadedAt"] = vector_set["updatedAt"]
        _mark_session_downloaded_if_complete(vector_set["testSessionId"])

    return with_skeleton_metadata(
        {
            "vectorSetId": vector_set_id,
            "testSessionId": vector_set["testSessionId"],
            "status": vector_set["status"],
            "prompt": vector_set["prompt"],
            "generatedFromCapabilities": vector_set.get("generatedFromCapabilities", False),
            "generationProfile": vector_set.get("generationProfile"),
            "campaignSeed": vector_set.get("campaignSeed"),
            "downloadedAt": vector_set.get("downloadedAt"),
            "expiresAt": vector_set.get("expiresAt"),
            "stateHistory": list(vector_set.get("stateHistory", [])),
        }
    )


def get_vector_set_expected_results(vector_set_id: str) -> Any:
    vector_set = _get_vector_set(vector_set_id)
    if isinstance(vector_set, JSONResponse):
        return vector_set
    path = f"/acvp/v1/vectorSets/{vector_set_id}/expectedResults"
    unavailable = _reject_if_vector_unavailable(vector_set, path)
    if isinstance(unavailable, JSONResponse):
        return unavailable
    if vector_set["expectedResults"] is None:
        return acvp_skeleton_error(
            409,
            "EXPECTED_RESULTS_NOT_READY",
            "Expected results are not available for this local skeleton vector set.",
            path,
        )

    return with_skeleton_metadata(
        {
            "vectorSetId": vector_set_id,
            "testSessionId": vector_set["testSessionId"],
            "expectedResults": vector_set["expectedResults"],
            "status": vector_set["status"],
            "expiresAt": vector_set.get("expiresAt"),
        }
    )


def submit_vector_set_results(vector_set_id: str, response: Any) -> Any:
    vector_set = _get_vector_set(vector_set_id)
    if isinstance(vector_set, JSONResponse):
        return vector_set
    path = f"/acvp/v1/vectorSets/{vector_set_id}/results"
    unavailable = _reject_if_vector_unavailable(vector_set, path)
    if isinstance(unavailable, JSONResponse):
        return unavailable
    if vector_set["status"] not in {
        VectorSetStatus.READY.value,
        VectorSetStatus.DOWNLOADED.value,
        VectorSetStatus.RESULTS_SUBMITTED.value,
        VectorSetStatus.VALIDATED.value,
        VectorSetStatus.FAILED.value,
    }:
        return acvp_skeleton_error(
            409,
            "VECTOR_SET_NOT_READY",
            "Vector set is not ready for result submission.",
            path,
        )
    session = ACVP_SKELETON_SESSION_STORE.get(vector_set["testSessionId"])
    if session is not None and session.get("submittedForValidation"):
        return acvp_skeleton_error(
            409,
            "VECTOR_SET_ALREADY_FINALIZED",
            "Vector set results cannot be changed after session submit-for-validation.",
            path,
        )
    if vector_set["expectedResults"] is None:
        return acvp_skeleton_error(
            409,
            "EXPECTED_RESULTS_NOT_READY",
            "Expected results must be generated before result submission in the local skeleton.",
            path,
        )

    mode = normalize_acvp_json(vector_set["prompt"]).get("mode")
    try:
        validate_mldsa_response(response, expected_mode=mode)
        bundle = {
            "prompt": vector_set["prompt"],
            "expectedResults": vector_set["expectedResults"],
            "response": response,
            "label": _get_session_label(vector_set["testSessionId"]),
        }
        validation_result = validate(bundle)
        report = build_report(vector_set_id, validation_result)
    except AcvpSchemaError as exc:
        return acvp_skeleton_error(400, exc.code, exc.message, exc.path)
    except ValueError as exc:
        return acvp_skeleton_error(400, "VALIDATION_ERROR", str(exc), "$")

    passed = _validation_passed(validation_result)
    final_status = (
        VectorSetStatus.VALIDATED.value
        if passed
        else VectorSetStatus.FAILED.value
    )
    try:
        _transition_vector_if_needed(
            vector_set,
            VectorSetStatus.RESULTS_SUBMITTED.value,
            reason="Vector set results submitted.",
        )
        vector_set["submittedAt"] = vector_set["updatedAt"]
        if session is not None:
            _transition_session_if_needed(
                session,
                TestSessionStatus.RESULTS_SUBMITTED.value,
                reason="At least one vector set result was submitted.",
                metadata={"vectorSetId": vector_set_id},
            )
        _transition_vector_if_needed(
            vector_set,
            VectorSetStatus.VALIDATING.value,
            reason="Vector set results are being synchronously validated.",
        )
        vector_set["validatingAt"] = vector_set["updatedAt"]
        vector_set["response"] = response
        vector_set["validationResult"] = validation_result
        vector_set["report"] = report
        _transition_vector_if_needed(
            vector_set,
            final_status,
            reason="Vector set results validated by local skeleton validator.",
            metadata={"passed": passed},
        )
        vector_set["validatedAt"] = vector_set["updatedAt"]
        if not passed:
            vector_set["failedAt"] = vector_set["updatedAt"]
        if session is not None:
            _apply_session_aggregate_status(session)
    except StateTransitionError as exc:
        return _state_transition_error_response(exc)

    return with_skeleton_metadata(
        {
            "vectorSetId": vector_set_id,
            "testSessionId": vector_set["testSessionId"],
            "status": vector_set["status"],
            "validationResult": validation_result,
            "report": report,
            "stateHistory": list(vector_set.get("stateHistory", [])),
        }
    )


def get_vector_set_results(vector_set_id: str) -> Any:
    vector_set = _get_vector_set(vector_set_id)
    if isinstance(vector_set, JSONResponse):
        return vector_set
    path = f"/acvp/v1/vectorSets/{vector_set_id}/results"
    unavailable = _reject_if_vector_unavailable(vector_set, path)
    if isinstance(unavailable, JSONResponse):
        return unavailable
    if vector_set["validationResult"] is None:
        return acvp_skeleton_error(
            409,
            "RESULTS_NOT_SUBMITTED",
            "Results have not been submitted for this vector set.",
            path,
        )

    return with_skeleton_metadata(
        {
            "vectorSetId": vector_set_id,
            "testSessionId": vector_set["testSessionId"],
            "status": vector_set["status"],
            "validationResult": vector_set["validationResult"],
            "report": vector_set["report"],
            "stateHistory": list(vector_set.get("stateHistory", [])),
        }
    )


def get_test_session_results(session_id: str) -> Any:
    session = _get_session(session_id)
    if isinstance(session, JSONResponse):
        return session
    path = f"/acvp/v1/testSessions/{session_id}/results"
    unavailable = _reject_if_session_unavailable(session, path)
    if isinstance(unavailable, JSONResponse):
        return unavailable
    if not session["vectorSetIds"] and session["status"] == TestSessionStatus.CAPABILITIES_ACCEPTED.value:
        return acvp_skeleton_error(
            409,
            "VECTOR_SETS_NOT_GENERATED",
            "This registration session has no vector sets yet. Generate vector sets before requesting results.",
            path,
        )

    vector_results = []
    for vector_set_id in session["vectorSetIds"]:
        vector_set = ACVP_SKELETON_VECTOR_SET_STORE.get(vector_set_id)
        if vector_set is None or vector_set["validationResult"] is None:
            continue
        vector_results.append(
            {
                "vectorSetId": vector_set_id,
                "status": vector_set["status"],
                "validationResult": vector_set["validationResult"],
                "report": vector_set["report"],
            }
        )

    if not vector_results:
        return acvp_skeleton_error(
            409,
            "RESULTS_NOT_SUBMITTED",
            "No vector set results have been submitted for this test session.",
            path,
        )

    return with_skeleton_metadata(
        {
            "testSessionId": session_id,
            "status": session["status"],
            "summary": _session_result_summary(session),
            "vectorSetResults": vector_results,
            "stateHistory": list(session.get("stateHistory", [])),
        }
    )


def submit_test_session_for_validation(session_id: str) -> Any:
    session = _get_session(session_id)
    if isinstance(session, JSONResponse):
        return session
    path = f"/acvp/v1/testSessions/{session_id}/submit"
    unavailable = _reject_if_session_unavailable(session, path)
    if isinstance(unavailable, JSONResponse):
        return unavailable
    if not session["vectorSetIds"] and session["status"] == TestSessionStatus.CAPABILITIES_ACCEPTED.value:
        return acvp_skeleton_error(
            409,
            "VECTOR_SETS_NOT_GENERATED",
            "This registration session has no vector sets yet. Generate vector sets before session submit.",
            path,
        )

    summary = _session_result_summary(session)
    if summary["submittedVectorSets"] == 0:
        return acvp_skeleton_error(
            409,
            "RESULTS_NOT_SUBMITTED",
            "No vector set results have been submitted for this test session.",
            path,
        )
    if summary["pendingVectorSets"] > 0:
        return acvp_skeleton_error(
            409,
            "VECTOR_SET_RESULTS_INCOMPLETE",
            "All vector set results must be submitted before session-level validation.",
            path,
        )

    if not session.get("submittedForValidation"):
        final_status = (
            TestSessionStatus.FAILED.value
            if summary["failedVectorSets"] > 0
            else TestSessionStatus.VALIDATED.value
        )
        try:
            _transition_session_if_needed(
                session,
                TestSessionStatus.VALIDATING.value,
                reason="Session submitted for validation.",
            )
            _transition_session_if_needed(
                session,
                final_status,
                reason="Session aggregate validation finalized.",
                metadata={"sessionPassed": final_status == TestSessionStatus.VALIDATED.value},
            )
        except StateTransitionError as exc:
            return _state_transition_error_response(exc)
        session["submittedForValidation"] = True
        session["submittedForValidationAt"] = session["updatedAt"]
        summary = _session_result_summary(session)

    return with_skeleton_metadata(
        {
            "testSessionId": session_id,
            "status": session["status"],
            "summary": summary,
            "submittedForValidation": session.get("submittedForValidation", False),
            "submittedForValidationAt": session.get("submittedForValidationAt"),
            "stateHistory": list(session.get("stateHistory", [])),
        }
    )


def delete_test_session(session_id: str) -> Any:
    session = _get_session(session_id)
    if isinstance(session, JSONResponse):
        return session
    path = f"/acvp/v1/testSessions/{session_id}"
    unavailable = _reject_if_session_unavailable(session, path, allow_cancelled=True)
    if isinstance(unavailable, JSONResponse):
        return unavailable

    if session["status"] != TestSessionStatus.CANCELLED.value:
        try:
            transition_session(
                session,
                TestSessionStatus.CANCELLED.value,
                reason="Test session cancelled by DELETE request.",
            )
            for vector_set_id in list(session["vectorSetIds"]):
                vector_set = ACVP_SKELETON_VECTOR_SET_STORE.get(vector_set_id)
                if vector_set is not None and not is_terminal_status(vector_set["status"]):
                    transition_vector_set(
                        vector_set,
                        VectorSetStatus.CANCELLED.value,
                        reason="Parent test session cancelled.",
                    )
                    vector_set["cancelledAt"] = vector_set["updatedAt"]
            session["cancelledAt"] = session["updatedAt"]
        except StateTransitionError as exc:
            return _state_transition_error_response(exc)

    return with_skeleton_metadata(
        {
            "cancelled": True,
            "testSessionId": session_id,
            "status": session["status"],
            "localSkeletonBehavior": True,
            "stateHistory": list(session.get("stateHistory", [])),
        }
    )


def cancel_vector_set(vector_set_id: str) -> Any:
    vector_set = _get_vector_set(vector_set_id)
    if isinstance(vector_set, JSONResponse):
        return vector_set
    path = f"/acvp/v1/vectorSets/{vector_set_id}"
    unavailable = _reject_if_vector_unavailable(vector_set, path, allow_cancelled=True)
    if isinstance(unavailable, JSONResponse):
        return unavailable

    if vector_set["status"] != VectorSetStatus.CANCELLED.value:
        try:
            transition_vector_set(
                vector_set,
                VectorSetStatus.CANCELLED.value,
                reason="Vector set cancelled by DELETE request.",
            )
            vector_set["cancelledAt"] = vector_set["updatedAt"]
            _cancel_session_if_all_vector_sets_cancelled(vector_set["testSessionId"])
        except StateTransitionError as exc:
            return _state_transition_error_response(exc)

    return with_skeleton_metadata(
        {
            "cancelled": vector_set["status"] == VectorSetStatus.CANCELLED.value,
            "vectorSetId": vector_set_id,
            "testSessionId": vector_set["testSessionId"],
            "status": vector_set["status"],
            "localSkeletonBehavior": True,
            "stateHistory": list(vector_set.get("stateHistory", [])),
        }
    )


def _get_session(session_id: str) -> Any:
    session = ACVP_SKELETON_SESSION_STORE.get(session_id)
    if session is None:
        return acvp_skeleton_error(
            404,
            "UNKNOWN_TEST_SESSION",
            "Unknown testSessionId.",
            f"/acvp/v1/testSessions/{session_id}",
        )
    return session


def _get_vector_set(vector_set_id: str) -> Any:
    vector_set = ACVP_SKELETON_VECTOR_SET_STORE.get(vector_set_id)
    if vector_set is None:
        return acvp_skeleton_error(
            404,
            "UNKNOWN_VECTOR_SET",
            "Unknown vectorSetId.",
            f"/acvp/v1/vectorSets/{vector_set_id}",
        )
    return vector_set


def _session_summary(session: Dict[str, Any]) -> Dict[str, Any]:
    vector_set_summaries = [
        _vector_set_summary(ACVP_SKELETON_VECTOR_SET_STORE[vector_set_id])
        for vector_set_id in session["vectorSetIds"]
        if vector_set_id in ACVP_SKELETON_VECTOR_SET_STORE
    ]
    first_summary = vector_set_summaries[0] if vector_set_summaries else {}
    result_summary = _session_result_summary(session)
    summary = {
        "testSessionId": session["testSessionId"],
        "createdAt": session["createdAt"],
        "updatedAt": session["updatedAt"],
        "expiresAt": session.get("expiresAt"),
        "status": session["status"],
        "label": session.get("label"),
        "vectorSetIds": list(session["vectorSetIds"]),
        "vectorSetUrls": list(session["vectorSetUrls"]),
        "vectorSetCount": len(session["vectorSetIds"]),
        "downloadedVectorSetCount": result_summary["downloadedVectorSets"],
        "submittedVectorSetCount": result_summary["submittedVectorSets"],
        "validatedVectorSetCount": result_summary["validatedVectorSets"],
        "failedVectorSetCount": result_summary["failedVectorSets"],
        "pendingVectorSetCount": result_summary["pendingVectorSets"],
        "algorithm": first_summary.get("algorithm"),
        "mode": first_summary.get("mode"),
        "revision": first_summary.get("revision"),
        "testGroupCount": first_summary.get("testGroupCount", 0),
        "testCaseCount": first_summary.get("testCaseCount", 0),
        "stateHistory": list(session.get("stateHistory", [])),
        **SKELETON_METADATA,
    }
    if "negotiatedCapabilities" in session:
        summary["negotiatedCapabilities"] = session["negotiatedCapabilities"]
        summary["negotiationWarnings"] = session.get("negotiationWarnings", [])
        summary["unsupported"] = session.get("unsupported", [])
        summary["nextAction"] = session.get("nextAction", VECTOR_GENERATION_AVAILABLE_ACTION)
    if "vectorGeneration" in session:
        summary["vectorGeneration"] = session["vectorGeneration"]
    return summary


def _vector_set_summary(vector_set: Dict[str, Any]) -> Dict[str, Any]:
    prompt_summary = summarize_vector_set(normalize_acvp_json(vector_set["prompt"]))
    return {
        "vectorSetId": vector_set["vectorSetId"],
        "testSessionId": vector_set["testSessionId"],
        "status": vector_set["status"],
        "url": f"/acvp/v1/vectorSets/{vector_set['vectorSetId']}",
        "generatedFromCapabilities": vector_set.get("generatedFromCapabilities", False),
        "generationProfile": vector_set.get("generationProfile"),
        "campaignSeed": vector_set.get("campaignSeed"),
        "mode": vector_set.get("mode", prompt_summary.get("mode")),
        "vsId": vector_set.get("vsId", prompt_summary.get("vsId")),
        "downloadedAt": vector_set.get("downloadedAt"),
        "submittedAt": vector_set.get("submittedAt"),
        "validatedAt": vector_set.get("validatedAt"),
        "failedAt": vector_set.get("failedAt"),
        "cancelledAt": vector_set.get("cancelledAt"),
        "expiresAt": vector_set.get("expiresAt"),
        "stateHistory": list(vector_set.get("stateHistory", [])),
        **prompt_summary,
        **SKELETON_METADATA,
    }


def _get_session_label(session_id: str) -> Optional[str]:
    session = ACVP_SKELETON_SESSION_STORE.get(session_id)
    if session is None:
        return None
    label = session.get("label")
    return str(label) if label is not None else None


def _validation_passed(validation_result: Dict[str, Any]) -> bool:
    summary = validation_result["summary"]
    return (
        summary["failed"] == 0
        and summary["missing"] == 0
        and summary["malformed"] == 0
        and summary.get("extra", 0) == 0
    )


def _record_created(entity: Dict[str, Any], to_status: str, reason: str) -> None:
    add_state_event(
        entity,
        event="created",
        from_status=None,
        to_status=to_status,
        reason=reason,
    )


def _transition_session_if_needed(
    session: Dict[str, Any],
    to_status: str,
    *,
    reason: str,
    metadata: Optional[Dict[str, Any]] = None,
) -> None:
    if session["status"] == to_status:
        return
    transition_session(session, to_status, reason=reason, metadata=metadata)


def _transition_vector_if_needed(
    vector_set: Dict[str, Any],
    to_status: str,
    *,
    reason: str,
    metadata: Optional[Dict[str, Any]] = None,
) -> None:
    if vector_set["status"] == to_status:
        return
    transition_vector_set(vector_set, to_status, reason=reason, metadata=metadata)


def _mark_session_downloaded_if_complete(session_id: str) -> None:
    session = ACVP_SKELETON_SESSION_STORE.get(session_id)
    if session is None or session["status"] != TestSessionStatus.VECTOR_READY.value:
        return
    vector_sets = _session_vector_sets(session)
    if not vector_sets:
        return
    if all(vector_set.get("downloadedAt") for vector_set in vector_sets):
        transition_session(
            session,
            TestSessionStatus.VECTOR_DOWNLOADED.value,
            reason="All vector sets have been downloaded.",
        )


def _apply_session_aggregate_status(session: Dict[str, Any]) -> None:
    summary = _session_result_summary(session)
    if summary["submittedVectorSets"] == 0:
        return
    if summary["pendingVectorSets"] > 0:
        _transition_session_if_needed(
            session,
            TestSessionStatus.RESULTS_SUBMITTED.value,
            reason="Some vector set results are submitted; other vector sets are pending.",
        )
        return

    final_status = (
        TestSessionStatus.FAILED.value
        if summary["failedVectorSets"] > 0
        else TestSessionStatus.VALIDATED.value
    )
    _transition_session_if_needed(
        session,
        TestSessionStatus.VALIDATING.value,
        reason="All vector set results are available for session aggregate validation.",
    )
    _transition_session_if_needed(
        session,
        final_status,
        reason="Session aggregate validation completed.",
        metadata={"sessionPassed": final_status == TestSessionStatus.VALIDATED.value},
    )


def _session_result_summary(session: Dict[str, Any]) -> Dict[str, Any]:
    vector_sets = _session_vector_sets(session)
    total = len(session.get("vectorSetIds", []))
    downloaded = sum(1 for vector_set in vector_sets if vector_set.get("downloadedAt"))
    submitted = sum(
        1
        for vector_set in vector_sets
        if vector_set.get("submittedAt") or vector_set.get("validationResult") is not None
    )
    validated = sum(
        1
        for vector_set in vector_sets
        if vector_set.get("status") == VectorSetStatus.VALIDATED.value
    )
    failed = sum(
        1
        for vector_set in vector_sets
        if vector_set.get("status") == VectorSetStatus.FAILED.value
    )
    pending = max(total - submitted, 0)
    session_passed = total > 0 and pending == 0 and failed == 0 and validated == total
    return {
        "totalVectorSets": total,
        "downloadedVectorSets": downloaded,
        "submittedVectorSets": submitted,
        "validatedVectorSets": validated,
        "passedVectorSets": validated,
        "failedVectorSets": failed,
        "pendingVectorSets": pending,
        "sessionPassed": session_passed,
    }


def _session_vector_sets(session: Dict[str, Any]) -> List[Dict[str, Any]]:
    return [
        ACVP_SKELETON_VECTOR_SET_STORE[vector_set_id]
        for vector_set_id in session.get("vectorSetIds", [])
        if vector_set_id in ACVP_SKELETON_VECTOR_SET_STORE
    ]


def _reject_if_session_unavailable(
    session: Dict[str, Any],
    path: str,
    *,
    allow_cancelled: bool = False,
) -> Optional[JSONResponse]:
    _expire_session_if_needed(session)
    if session["status"] == TestSessionStatus.EXPIRED.value:
        return acvp_skeleton_error(
            409,
            "TEST_SESSION_EXPIRED",
            "Test session has expired in the local skeleton state machine.",
            path,
        )
    if session["status"] == TestSessionStatus.CANCELLED.value and not allow_cancelled:
        return acvp_skeleton_error(
            409,
            "TEST_SESSION_CANCELLED",
            "Test session has been cancelled.",
            path,
        )
    return None


def _reject_if_vector_unavailable(
    vector_set: Dict[str, Any],
    path: str,
    *,
    allow_cancelled: bool = False,
) -> Optional[JSONResponse]:
    session = ACVP_SKELETON_SESSION_STORE.get(vector_set["testSessionId"])
    if session is not None:
        session_error = _reject_if_session_unavailable(
            session,
            path,
            allow_cancelled=allow_cancelled,
        )
        if isinstance(session_error, JSONResponse):
            return session_error

    _expire_vector_set_if_needed(vector_set)
    if vector_set["status"] == VectorSetStatus.EXPIRED.value:
        return acvp_skeleton_error(
            409,
            "VECTOR_SET_EXPIRED",
            "Vector set has expired in the local skeleton state machine.",
            path,
        )
    if vector_set["status"] == VectorSetStatus.CANCELLED.value and not allow_cancelled:
        return acvp_skeleton_error(
            409,
            "VECTOR_SET_CANCELLED",
            "Vector set has been cancelled.",
            path,
        )
    return None


def _expire_session_if_needed(session: Dict[str, Any]) -> bool:
    if is_terminal_status(session["status"]) or not session_is_expired(session):
        return False
    transition_session(
        session,
        TestSessionStatus.EXPIRED.value,
        reason="Test session expiresAt was reached.",
    )
    session["expiredAt"] = session["updatedAt"]
    for vector_set in _session_vector_sets(session):
        if not is_terminal_status(vector_set["status"]):
            transition_vector_set(
                vector_set,
                VectorSetStatus.EXPIRED.value,
                reason="Parent test session expired.",
            )
            vector_set["expiredAt"] = vector_set["updatedAt"]
    return True


def _expire_vector_set_if_needed(vector_set: Dict[str, Any]) -> bool:
    if is_terminal_status(vector_set["status"]) or not vector_set_is_expired(vector_set):
        return False
    transition_vector_set(
        vector_set,
        VectorSetStatus.EXPIRED.value,
        reason="Vector set expiresAt was reached.",
    )
    vector_set["expiredAt"] = vector_set["updatedAt"]
    session = ACVP_SKELETON_SESSION_STORE.get(vector_set["testSessionId"])
    if session is not None and not is_terminal_status(session["status"]):
        vector_sets = _session_vector_sets(session)
        if vector_sets and all(
            item["status"] == VectorSetStatus.EXPIRED.value for item in vector_sets
        ):
            transition_session(
                session,
                TestSessionStatus.EXPIRED.value,
                reason="All vector sets in the session expired.",
            )
            session["expiredAt"] = session["updatedAt"]
    return True


def _cancel_session_if_all_vector_sets_cancelled(session_id: str) -> None:
    session = ACVP_SKELETON_SESSION_STORE.get(session_id)
    if session is None or is_terminal_status(session["status"]):
        return
    vector_sets = _session_vector_sets(session)
    if vector_sets and all(
        vector_set["status"] == VectorSetStatus.CANCELLED.value
        for vector_set in vector_sets
    ):
        transition_session(
            session,
            TestSessionStatus.CANCELLED.value,
            reason="All vector sets in the session were cancelled.",
        )
        session["cancelledAt"] = session["updatedAt"]


def _state_transition_error_response(exc: StateTransitionError) -> JSONResponse:
    return acvp_skeleton_error(409, exc.code, exc.message, exc.path)


def _expires_at_from_seconds(expires_in_seconds: Optional[int]) -> Optional[str]:
    if expires_in_seconds is None:
        return None
    return (datetime.now(timezone.utc) + timedelta(seconds=expires_in_seconds)).isoformat()


def _timestamp() -> str:
    return now_timestamp()
